---
title: "Cómo leer los metadatos de las imágenes de la cámara Sequoia y decodificar la etiqueta IrradianceList"
author: "Joan Cano"
output: html_document
---
## Tipos de metadatos en imágenes

Los metadatos son datos que nos proporcionan información sobre los datos, entre ellos los descriptivos, estructurales y administrativos.
Estos pueden ser escritos en iḿagenes como las que toma nuestra cámara, que ayudarán en el proceso posterior de producción a partir de palabras clave.

Las imágenes pueden contener diferentes metadatos, regidos por las normas creadas por organizaciones encargadas de ello; algunas de estas normas son:
* IPTC
* IPTC para XMP
* **XMP**
* **EXIF**
* Dublin Core
* PLUS
* VRA

## Liberías de lecturas de metadatos: Exiftools
Al haber tratado ya los metadatos de las imágenes de la [Sequoia](http://tecnitop.com/es/camaras-accesorios-y-software/), avanzo la necesidad de interpretar metadatos del estandar [XMP](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform#Free_software_and_open-source_tools_.28read.2Fwrite_support.29), una marca registrada por Adobe Systems que cuando pasó a ser ISO, dejó se ser propietaria.

Por lo tanto, necesitaremos buscar un software (libre) capaz de leer XMP, a continuación los que he probado:
* [GIMP](https://www.gimp.org/)
* [digiKam](https://www.digikam.org/)
* [ExifTool](https://www.sno.phy.queensu.ca/~phil/exiftool/)
* [ImageMagick](https://www.imagemagick.org/script/index.php)
GIMP y ImageMagick vienen por defecto en Debian. Un ejemplo de uso de ImageMagick vía terminal sería:
`Esto es codigo`


## Lectura de los metadatos:

### Desde R con Exifr

### Desde python con Exiftools

## Decodificar formato Base64 mediante Python

## Resultados


```{r}
library(rPython)
 
# Load/run the main Python script
python.load("GetNewRedditSubmissions.py")
```